el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.ImageView\").instance(13)")
el1.click()
el3 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/jxi")
el3.click()
el4 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/c4u")
el4.send_keys("@camglocks300")
el5 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/jvt")
el5.click()
el6 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().text(\"Videos\")")
el6.click()
el7 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/k1f")
el7.click()
el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().text(\"2979\")")
el8.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(529, 2298)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()

el9 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/c76")
el9.click()
el10 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/c76")
el10.click()
el12 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/dqx")
el12.click()
el13 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/dqx")
el13.click()
el14 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.ImageView\").instance(0)")
el14.click()
el15 = driver.find_element(by=AppiumBy.ID, value="com.zhiliaoapp.musically:id/dqx")
el15.click()
package_name = driver.execute_script('mobile: getCurrentPackage')
desired_caps = driver.desired_capabilities()
